name: wisdom
description: Wisdom – Flutter-app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Arkitektur
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Backend/infra
  dio: ^5.4.3
  http: ^1.2.2
  desktop_drop: ^0.5.0
  cross_file: ^0.3.3+2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  mime: ^1.0.5

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.2
  firebase_remote_config: ^5.0.5

  # UI
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_markdown: ^0.7.3
  file_selector: ^1.0.3
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0
  file_picker: ^8.0.0
  video_player: ^2.8.3
  uuid: ^4.4.2
  http_parser: ^4.0.2
  equatable: ^2.0.5
  flutter_stripe: ^12.0.2
  path_provider: ^2.1.4
  crypto: ^3.0.3
  flutter_quill: ^11.4.2
  markdown: ^7.3.0
  markdown_quill: ^4.3.0
  livekit_client: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/bakgrund.png
    - assets/loggo_clea.png
    - assets/icons/
    - assets/images/
    - assets/images/courses/
    - .env
